### ISSUE TITLE
Persistent sleep timer

### ISSUE THREAD

**Issue by kentmartin73** [prologueapp/Prologue#10]
Hi,

It would be great if the sleep timer was persistent, or had an option to make it so. By this I mean, turn it on and it’ll be in place every time you hit play until you turn it off.

Having just come over from Android, where I used Smart Audiobook Player, this is a feature I really miss, and use it every night in conjunction with a remote or shake to extend.

Thanks,

Kent

**Comment by genularity** [comment]
Hi,

I was excited to see this was closed in the latest update, but it doesn't seem to be working - perhaps it wasn't well explained.

Step 1: Play a book
Step 2: Set a sleep timer (say 10 minutes)
Step 3: Sleep timer expires, playback stops
Step 4: Press play
Step 5: No need to set another sleep timer, the sleep timer set at step 2 is still set (10 minutes)
Step 6: 10 minutes later, new sleep timer expires
GOTO Step 4

Is this the feature that is supposed to be implemented. If so, it isn't working for me.

Thanks,

Kent

**Comment by genularity** [comment]
Please note that this is the sole feature that prevents me using Prologue - were it not for this, it'd be used every single day
