### ISSUE TITLE
Error on login on server with Podcast library

### ISSUE THREAD

**Issue by vicegold** [prologueapp/Prologue#24]
Whenever I try to login into my ABS server I'm getting the error seen on the screen

![image](https://github.com/user-attachments/assets/c28f6b26-9dc7-47d3-9090-c15f4a55bb04)

**Comment by lcharlick** [comment]
This should be fixed in build 10003. Can you update and try again?
[Relevant ABSKit commit](https://github.com/lcharlick/AudiobookshelfKit/commit/064947fb4ee41dc307840c44046e16f3110b682a)

**Comment by vicegold** [comment]
That fixed it, thanks!
