### ISSUE TITLE
Cant jump to chapters & Progress Bar jumps between chapters

### ISSUE THREAD

**Issue by Yeradon** [prologueapp/Prologue#33]
First video shows the progress bar jumping. The Second shows me clicking the chapter buttons (clicking them has no effect on the audio playing, but seems to change smth in the progress bar).

https://drive.proton.me/urls/2THXVJQVKG#780BMggkIkVf

![chapter_progress](https://github.com/user-attachments/assets/c34ed8cd-bc7e-4352-931e-d3cfe4ac9705)

https://drive.proton.me/urls/FWWKXG342M#bot7PALU2yJe

![chapter_button](https://github.com/user-attachments/assets/d741b032-37a5-4fc3-9c3c-34a6eed63004)

**Comment by lcharlick** [comment]
Strange. Does this happen with all books, or just that one? 
Can you please recreate this, then send me an issue report from Settings > Report an Issue?

**Comment by Yeradon** [comment]
It happens on multiple books. They are all single m4b files with embedded chapters (created via abs tools). I usually have to start playback and then just click some of the chapter buttons to recreate it. Evantually the progress bar jumps around.

**Comment by lcharlick** [comment]
Can you try again on build 10011 when you get a chance? Let me know if it's still happening.

**Comment by Yeradon** [comment]
Seems like it is fixed. Still clicking the chapters doesnt make it jump to the chapter, idk if thats intended or not.

**Comment by lcharlick** [comment]
Tap to play chapter just hasn't been implemented yet. I've made #38 to track that.
