### ISSUE TITLE
Unable to authenticate to ABS server using OIDC

### ISSUE THREAD

**Issue by Nuuki9** [prologueapp/Prologue#39]
Audiobookshelf supports OpenID Connect (OIDC), to allow authentication via a Single Sign-On account, instead of needing to separately configure local accounts. Currently I'm not able to authenticate to ABS in Prologue via OIDC.

**Comment by yeyeoke** [comment]
Yeah i’m having the same issue. Would love to ditch ShelfPlayer for Prologue so I very much hope to see support for OIDC-based login.

**Comment by lcharlick** [comment]
Thanks, I'll try to get this in soon.

Note to self: https://api.audiobookshelf.org/#oauth2-authorization-request

**Comment by zacaronii** [comment]
Just wanted to leave a note here that I was able to authenticate successfully using OIDC. You just have to go to the mobile redirect uris section in ABS authentication settings and add prologue://oauth to it.
![image](https://github.com/user-attachments/assets/4ee80ebb-5206-4c20-858d-bc7873f16d33)

edit: I'm actually just an idiot and this doesn't work, currently. Apologies for the misinformation.

**Comment by Nuuki9** [comment]
Thanks for the info @zacaronii

Sadly I'm still having issues. I've added the mobile redirect as you indicated:

<img width="292" alt="image" src="https://github.com/user-attachments/assets/5b78254f-ac44-4952-9dd7-1b87cf8fa339">

But when I try to login via Prologue using the OIDC details, I get "Incorrect username or password". These are my logs from ABS:

```
[2024-10-23 12:59:13.443] ERROR: [Auth] Failed login attempt for username "userA" from ip 192.168.1.164 (Invalid password)
[2024-10-23 12:59:52.628] INFO: [SocketAuthority] Socket Connected N3XfsFhLk2s2AoxwAAAB
[2024-10-23 12:59:57.933] INFO: [SocketAuthority] Socket N3XfsFhLk2s2AoxwAAAB disconnected from client "userA" after 5305ms (Reason: transport close)
```

The first line is me trying to login using Prologue. The second/third lines are me logging in via a browser and then switching to a different app. Can you think of something obvious I'm missing?

**Comment by yeyeoke** [comment]
Yea I've tried this as well, I don't really see how this is supposed to work since Prologue doesn't know to send you to a webpage where you authenticate.

**Comment by zacaronii** [comment]
Looks like I'll have to accept the egg on my face for this one. Turns out I still had password authentication enabled and it was actually using my native ABS login. I filled the credentials from my password manager, and I didn't realize my mistake until taking a closer look at it, following your comments. 

I did attempt to go into the mobile redirect URIs and input an asterisk as the only entry, which should allow any mobile redirect to work. However, that still didn't work. Apologies for the misinformation on my part.

**Comment by Nuuki9** [comment]
@zacaronii No worries - good to know I wasn't just missing something obvious. I guess we stick with local auth for now, until OIDC is fully implemented.

**Comment by miiraheart** [comment]
> Just wanted to leave a note here that I was able to authenticate successfully using OIDC. You just have to go to the mobile redirect uris section in ABS authentication settings and add prologue://oauth to it. ![image](https://private-user-images.githubusercontent.com/156740629/378142270-4ee80ebb-5206-4c20-858d-bc7873f16d33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NTY0MjgsIm5iZiI6MTczMzk1NjEyOCwicGF0aCI6Ii8xNTY3NDA2MjkvMzc4MTQyMjcwLTRlZTgwZWJiLTUyMDYtNGMyMC04NThkLWJjNzg3M2YxNmQzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQyMjI4NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGE0N2VlMmQ2NzM3NDdiODE1NmRhM2QzZmNmMTNlMjYwNjkwMzM0MWY4YzM5YzFlODhjOWQ3MmUwN2M1NGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8vrEgVLhmwhZJZ5ZR1-Dpcf2xBVy5LlTHQ_HrzuoefQ)
> 
> edit: I'm actually just an idiot and this doesn't work, currently. Apologies for the misinformation.

humm, I just tried this and it worked

Edit: more details : I have authelia in front of abs and using prologue://oauth worked for me, it did not work like a week ago though and I did not change anyhing other that this option on my server

**Comment by lcharlick** [comment]
OK, after messing around with this for way too long I think I have it working, at least with my janky setup. Please give build 10078 a go and report back. 

If the server allows both OpenID and password auth, Prologue will present both as an option.

Note you’ll have to add `prologue://oauth` to Audiobookshelf’s “Allowed Mobile Redirect URIs” setting first. Prologue *should* detect and warn you if it's missing.

**Comment by Nuuki9** [comment]
Great work! Just tested it and I can now login via OIDC just fine. The lack of collections might stop this being my daily driver, but I'll certainly do more testing, and look forward to further updates.

**Comment by traktuner** [comment]
Hey @lcharlick, OAUTH works for me on the web app, but not on mobile. prologue://oauth is set, but I still get the warning in the app that I have to add the string to “Allowed Mobile Redirect URIs”.
Server was rebooted.
Any ideas how to diagnose this?
Thank you!
