### ISSUE TITLE
Podcast library not showing

### ISSUE THREAD

**Issue by aia832003** [prologueapp/Prologue#45]
I installed the new alpha and I have two libraries: Audiobooks and Podcasts. The initial setup synced my Audiobook library but doesn't show or allow switching to Podcasts.

**Comment by lcharlick** [comment]
Prologue will only support audiobook libraries, at least for now.

**Comment by gh57gh** [comment]
My problem goes a bit further. First I had only my audiobook library in abs. prologue was working fine. when I added a second podcast library in abs prologue stopped showing me any library and saying no libraries are available… is that the case when having more than an audiobook library that no library shows at all?
