### ISSUE TITLE
Incorrect ordering of tracks in large albums

### ISSUE THREAD

**Issue by excursus** [prologueapp/Prologue#5]
Albums containing large numbers of files sometimes show tracks out of order. The order I have observed in an album containing ~1600 tracks is:
```
1024
256
768
512
1025
...
```
The pattern suggests integer overflow (possibly with track name ordering in order to break ties).

This may be a fairly remote corner case, although perhaps not so remote considering that some pretty popular books (the bible?) may be split up into large numbers of tracks.

**Comment by YourMJK** [comment]
Does it show the correct order when you look at the album in Plex?
