### ISSUE TITLE
No Embedded Chapters Metadata Guide

### ISSUE THREAD

**Issue by aabeba** [prologueapp/Prologue#6]
This is more related to documentation... But will you update the MP4 and MP3 sections of Metadata Guide? I have looked far and wide for a tool that allows me to edit or even view the chapter metadata in an MP3 file. How on Earth is Prologue able to read chapters from a single MP3 audiobook without a CUE sheet? I can't see any chapter metadata in Windows Explorer, Mp3tag, or anything else. A pointer would be much appreciated.

**Comment by TheMetalCenter** [comment]
> I have looked far and wide for a tool that allows me to edit or even view the chapter metadata in an MP3 file. How on Earth is Prologue able to read chapters from a single MP3 audiobook without a CUE sheet? I can't see any chapter metadata in Windows Explorer, Mp3tag, or anything else. A pointer would be much appreciated.

Prologue is reading id3v2 tags in mp3 files that contain chapter information. Very few programs can read these, ffmpeg is one. [This repository ](https://github.com/TheMetalCenter/m4b-mp3-chapters-from-cuesheets) provides a working (albeit somewhat convoluted) method to modify them on Windows.

**Comment by YourMJK** [comment]
Sorry for the late response. I will try to update the wiki soon.

For MP3 files, the `CHAP` and `CTOC` (table of contents) tags are used. The latter one is required to be present.

The easiest way I have found (which is also the one I regularly use) to embed chapter metadata in MP3s is by using `ffmpeg` and a text file in the [`ffmetadata`](https://ffmpeg.org/ffmpeg-formats.html#Metadata-1) format.  
But I'm sure there are many other tools that can do this as well.
