### ISSUE TITLE
Can't exit player view in landscape

### ISSUE THREAD

**Issue by wesleyeff** [prologueapp/Prologue#62]
If you turn your phone sideways and then open the player view you can't exit the player view. At least I can't figure out how is there is a way. Swiping down doesn't work. 

Also would you consider having an option to disable landscape view entirely?

**Comment by lcharlick** [comment]
Yep, I didn't intend to enable landscape mode. Kinda surprised by how well it works all things considered 😅

**Comment by lcharlick** [comment]
Landscape mode has been disabled in build 10026
