### ISSUE TITLE
Can’t login with ABS 2.13.3

### ISSUE THREAD

**Issue by mandrepont** [prologueapp/Prologue#63]
I think ABS might have messed up their API but, if they did not then perhaps make this field optional. 

Duration used to be 0 but now can be nil so it throws an error trying to decode on login.

**Comment by lcharlick** [comment]
I can't recreate this on v2.13.3. I'm guessing it's `mediaProgress.duration` that's causing the error?

**Comment by mandrepont** [comment]
Yep that is the issue. When you get down the coding keys it's 
user -> mediaProgress -> duration

**Comment by th0mcat** [comment]
Can confirm.

![IMG_1669](https://github.com/user-attachments/assets/fb9bda66-e663-461b-b217-eb99ec374c84)

**Comment by lcharlick** [comment]
Should be fixed in build 10026. Reopen if there are still issues. Thanks!
