### ISSUE TITLE
Pause/Continue Reading button only works when text it tapped

### ISSUE THREAD

**Issue by csandman** [prologueapp/Prologue#7]
I noticed that when you are looking at a book's page while it is playing the "Continue Reading" button turns into a "Pause" button, but if you tap on the button anywhere but the text itself (the "Pause" text) it doesn't do anything.  This is very minor but it feels like bad UX when the button extends the full width of the screen and a large portion of it is not tap-able.

![IMG_8018](https://user-images.githubusercontent.com/9214195/151894322-6a1b3207-d788-4723-8650-b06a5b8f38c7.PNG)

**Comment by YourMJK** [comment]
This seems to have been fixed since. At least I can't replicate it in the latest beta version.

Thanks for reporting it!
