### ISSUE TITLE
Unable to add server

### ISSUE THREAD

**Issue by kemko** [prologueapp/Prologue#71]
Fresh Prologue installation asks me to add servers on first launch. When I try to add my own ABS server `audiobookshelf.kemko.dev` the app show red exclamation mark in address field and sign in button stay gray.

I don't see any http(s) requests from the app before the error mark appeared. It appears very fast so it is not any kind of timeout. Also, I am successfully using the audiobookshelf from browser on Mac via the same connection.

How can I fix this?

iPhone 15 Pro Max, iOS 18.0.1
Prologue 2024.4.0 (10028)
ABS 2.15.1

**Comment by Unending** [comment]
Can't know exactly how prologue checks a server, but most likely [this way](https://api.audiobookshelf.org/#check-the-server-39-s-status).

I receive a request at `_ABS_URL_/ping` which returns `{"success":true}`. Your server returns `pong`.

I'm guessing somewhere in your setup you have a webserver, reverse proxy or something else that interferes or intercepts these requests?

**Comment by kemko** [comment]
@Unending thanks for your help, this turned out to be the actual problem. It seems there's some response caching, which is why I couldn't see anything through tcpdump.

**Comment by fogost** [comment]
I have the same problem, my ABS server is only accessible from private network, should it be public?
