### ISSUE TITLE
Collections no longer Sync after Plex Update 

### ISSUE THREAD

**Issue by Javagedes** [prologueapp/Prologue#74]
Currently I host a Plex server via TrueNAS via a plugin. I recently updated Plex, which broke collection syncing from Plex to the app. Existing collections continue to exist, but adding new collections, or new books to existing collections will not show up on prologue (The book is appears, just does not sync). 

It looks like I'm not the only one effected. I was able to find a reddit post regarding this in the past few days. Hopefully I'm not spamming you with an issue that has already been reported multiple times. I did not see one here.

https://www.reddit.com/r/PrologueApp/comments/1gwp774/missing_collections/

Versions:
- Prologue: 3.5.7 (9504)
- Plex: 1.41.2.9200
- TrueNAS: TrueNAS-13.0-U6.3

**Comment by lcharlick** [comment]
Thanks for reporting. Should be fixed in 3.5.8, which I'll submit today.

**Comment by Javagedes** [comment]
@lcharlick apoligies for the duplicate - I appreciate the quick response!
