### ISSUE TITLE
Double Playback

### ISSUE THREAD

**Issue by slslazy** [prologueapp/Prologue#8]
It’s not a big deal but if you play a book, then download the book, two instances of the audio overlap and only one can be paused until the app is closed.

**Comment by YourMJK** [comment]
Can't replicate the issue.

What version are you on and does it happen with MP3 files, MP4 files or both?

Did you try it in the new version 3.3.0?

**Comment by slslazy** [comment]
Yup, 3.3. It's definitely intermittent but only happens when I try to download and play at the same time. Recorded it this time. https://drive.google.com/file/d/1usMyxABBDOV_GDvq5TulxrAphRRxpBFO/view?usp=drivesdk
